language: node_js
node_js:
- lts/dubnium
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: g+rXGZrL9V5lpPqvJxIkClWraV+Tec5d7vwXDL5dkV7vnO5nr6Kxa9lmWcq8a5YPNVQ+7y0QIIBg4hFmPH6dXfVVdNyrf7x+pb3CLukb/yhngLRaetmGiv7kLizKPZ9C15eBrWyqJLujrL7Zq7R9Sw7DB0bMDyf82e9NCD93c0J9Bz9y1ATie428Tp3/yQ7UswohihcWtja03/R+bNUmvU4iX9szdHatcESP7Us1RtZPosTXuQtgNviDGpQaE83FeK3p0zk682Y45F/zp8ytfGoqsw0vu0WyoxJo9LGkpFOD+NkKPqD6e/LLG1Cbw2OvpXHlSvLH0xzcRfGPxM8x3kDnFFfyu6oVXZ426zhQUfRN9qH/qsU2ukR5zGAVExp+7Uy2Y/sji6VRD97vMHFZFZTM9Ir+r8MdoJrGyjsGxo+UlAR03klT0GgrNt16D3jxA4WbypEcRdVzKngpiKLe+UZPudOOfSpG1CThIt1EpVNcqq1W94HHLarn62+rjWHL4lxBknwkWxcfnWrMXtXylq9XJVaxJHVHPeaP1Ry1lWRyhjj8HBds23FFzS/5vKRVcU1B+bUrGW/kBG11hYMDe3bkFaHZe1OonnGmIF0v+E87uYOAmf7p1IN1oKRwShtRrwY/pX0sHXQnTWqfU6Vox3RKZfzZv9oGXq0ZcB0hSoU=
  file:
    - "character-reference-invalid.js"
    - "character-reference-invalid.min.js"
  on:
    tags: true
