language: node_js
node_js:
- '4.0'
- '8.0'
deploy:
  provider: releases
  api_key:
    secure: dp5f4119Fj+cdZae1IJHR8XpasriYAuRg47NTy8sQ9yJ2dsNg/hd4zqKVnldD0PnVINNHlYnlDtABbx/hAr2okFSWmkm8qn1D1yt5jztH0Fx87bq6MIry3OTz8bFAnilbGnMoCk7/gcJYRZAGRjqsHqfJWMJwDm70dPeMyCQUAyR4/0mu9PnhIwPmNAbQFPAxcj/42UtxTqS2zauqngZibzU6C8X/Uzc7w54ooze29bNGDzwv3p3lpJdcYVwB8+19rE8w77/Lbdt66chzTGqGJrhVDrlXyRA1kDIRhRaJirwhB6gPbuPTP4DQCQIcE7TDzrOrp8nNqYISTawQxMhAWwBxTSzUABqf8pqenwlNjTDQ2AK+dWzuV5Qg7uawsl0KXuy1uFn8J+GXWdSylCfYRYf/FaprIoYkBNzFFA56C6Tu3lY3KE8G0t7zqtdEaMCqHGKGOBvl65eXWcx36LFeCUs/w6ZcqPl2N4ysIzSkrEjhAkJxZHz3tnwiM6X3zcoI8HJRetsCduaWG8vj883dj2t7TDorZyV0U2K5z+yTNtACy9QUSAJdDTj3+f5KI6wL0eOs36ysCsm2symbmMVLPPlRAK8YOE9lEd9XWo7RSLc0rN3k8N6OjyfoCojR3UGIiK7RgXUJ4FmDvUHBXnY5Op24RGL1bRTHLbw8GvGFHE=
  file:
    - "character-reference-invalid.js"
    - "character-reference-invalid.min.js"
  on:
    tags: true
    node: '8.0'
